#!/usr/bin/env bash

##### START COMPONENT CONFIGURATION #####
export SOLECO_MODULE="package.rest_elasticsearch"
export SOLECO_MODULE_VERSION=""
export VCW_SOLUTON_HIDE_COMPONENT="true"
##### END COMPONENT CONFIGURATION #####
